language: go
cache:
  directories:
    - $GOPATH/pkg/mod
go:
  - 1.15.x
env:
  - GO111MODULE=on
script:
  - make
before_deploy:
  - make VERSION=${TRAVIS_TAG} release -j2
deploy:
  provider: releases
  api_key:
    secure:
  file: release/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true