name: Release binaries

on:
  release:
    types: [created]

env:
  CMD_PATH: ./cmd/jmmrcp

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@latest
    
    - name: Set APP_VERSION env
    run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - name: Set BUILD_TIME env
    run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}
    - name: Environment Printer
    uses: managedkaos/print-env@latest
    
    - uses: wangyoucao577/go-release-action@latest
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "."
        binary_name: "justicia"
        build_flags: -v -s -w
        ldflags: -X "main.appVersion=${{ env.APP_VERSION }}" -X "main.buildTime=${{ env.BUILD_TIME }}" -X main.gitCommit=${{ github.sha }} -X main.gitRef=${{ github.ref }}
        extra_files: LICENSE